# postgres.ps1 - Steps 8-9: PostgreSQL install + DB bootstrap.

function Test-PostgresInstalled {
    # Match any installed PostgreSQL service (v14/15/16/17), not just v15, so an
    # existing PostgreSQL is reused instead of conflicting on port 5432.
    $svc = Get-Service -Name 'postgresql-x64-*' -ErrorAction SilentlyContinue
    return [bool]$svc
}

function Get-PsqlPath {
    $candidates = @(
        'C:\Program Files\PostgreSQL\17\bin\psql.exe',
        'C:\Program Files\PostgreSQL\16\bin\psql.exe',
        'C:\Program Files\PostgreSQL\15\bin\psql.exe',
        'C:\Program Files\PostgreSQL\14\bin\psql.exe'
    )
    foreach ($p in $candidates) { if (Test-Path $p) { return $p } }
    return $null
}

function Install-PostgreSQL {
    param(
        [Parameter(Mandatory)][string]$InstallerExe,
        [Parameter(Mandatory)][string]$SuperPassword,
        [string]$DataDir = 'C:\Program Files\PostgreSQL\15\data',
        [int]$Port = 5432
    )
    Write-StepHeader -Number 8 -Total 25 -Title 'Installing PostgreSQL 15 (this takes 3-5 minutes)'

    if (Test-PostgresInstalled) {
        Write-Log -Level OK -Message 'PostgreSQL service already installed; skipping install.'
        # An existing PostgreSQL has its OWN superuser password, which will not
        # match the one the wizard generated for THIS install. If we proceed
        # blindly the DB bootstrap (Step 9), migration, and user-seed all fail
        # with cryptic auth errors and login never works. Probe now and give a
        # clear, actionable message instead.
        $psql = Get-PsqlPath
        if ($psql) {
            $env:PGPASSWORD = $SuperPassword
            try {
                & $psql -h 127.0.0.1 -p $Port -U postgres -tA -c 'SELECT 1' 2>$null | Out-Null
                $authOk = ($LASTEXITCODE -eq 0)
            } finally {
                Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue
            }
            if (-not $authOk) {
                Write-Banner -Status STOP -Message ("An EXISTING PostgreSQL is installed and its 'postgres' superuser password does NOT match the one generated by this installer. " +
                    "FlowAccel cannot create its database with the wrong password. Fix one of these, then re-run:`r`n" +
                    "  (a) Uninstall the existing PostgreSQL (and delete its data dir) so FlowAccel can install a fresh one, OR`r`n" +
                    "  (b) Put the existing postgres password into config.json -> PgSuperPassword and run with /CONFIG.")
                throw 'Existing PostgreSQL superuser password mismatch - see message above.'
            }
            Write-Log -Level OK -Message 'Existing PostgreSQL superuser password verified.'
        } else {
            Write-Log -Level WARN -Message 'Existing PostgreSQL service found but psql.exe not located - cannot verify password. DB steps may fail.'
        }
        return
    }
    if (-not (Test-Path $InstallerExe)) { throw "PostgreSQL installer not found: $InstallerExe" }

    $args = @(
        '--mode','unattended',
        '--unattendedmodeui','none',
        '--superpassword', $SuperPassword,
        '--servicename','postgresql-x64-15',
        '--serviceaccount','postgres',
        '--servicepassword', $SuperPassword,
        '--serverport', "$Port",
        '--datadir', "`"$DataDir`""
    )
    Write-Log -Level INFO -Message 'Running PostgreSQL unattended installer...'
    $p = Start-Process -FilePath $InstallerExe -ArgumentList $args -Wait -PassThru
    if ($p.ExitCode -ne 0) { throw "PostgreSQL install failed with exit code $($p.ExitCode)." }

    # Wait for service to come online
    $svc = Get-Service postgresql-x64-15 -ErrorAction Stop
    if ($svc.Status -ne 'Running') { Start-Service postgresql-x64-15 }
    $svc.WaitForStatus('Running','00:01:00')
    Write-Log -Level OK -Message 'PostgreSQL 15 installed and running.'
}

function Initialize-AppDatabase {
    param(
        [Parameter(Mandatory)][string]$SuperPassword,
        [Parameter(Mandatory)][string]$AppDbPassword,
        [string]$DbName = 'jotflow',
        [string]$DbUser = 'jotflow',
        [int]$Port = 5432
    )
    Write-StepHeader -Number 9 -Total 25 -Title "Creating application database '$DbName'"
    $psql = Get-PsqlPath
    if (-not $psql) { throw 'psql.exe not found; PostgreSQL install incomplete.' }

    $env:PGPASSWORD = $SuperPassword
    try {
        $existing = & $psql -h 127.0.0.1 -p $Port -U postgres -tA -c "SELECT 1 FROM pg_database WHERE datname='$DbName'" 2>$null
        if ($existing -eq '1') {
            Write-Log -Level OK -Message "Database '$DbName' already exists; skipping create."
        } else {
            $sql = @"
CREATE USER $DbUser WITH PASSWORD '$AppDbPassword';
CREATE DATABASE $DbName OWNER $DbUser;
GRANT ALL PRIVILEGES ON DATABASE $DbName TO $DbUser;
"@
            $tmp = New-TemporaryFile
            Set-Content -Path $tmp -Value $sql -Encoding ASCII
            & $psql -h 127.0.0.1 -p $Port -U postgres -f $tmp.FullName 2>&1 |
                ForEach-Object { Write-Log -Level DEBUG -Message $_ }
            if ($LASTEXITCODE -ne 0) { throw "DB bootstrap failed (exit $LASTEXITCODE)" }
            Remove-Item $tmp -Force
            # Signal the orchestrator that THIS run created the DB/role, so an
            # abort-rollback may safely drop them. A pre-existing DB (the skip
            # branch above) leaves this flag false and is never dropped.
            $script:DbCreatedThisRun = $true
            Write-Log -Level OK -Message "Database '$DbName' and user '$DbUser' created."
        }
    } finally {
        Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue
    }
}

function Set-PgAdminAutoConnect {
    # Pre-register the FlowAccel database in pgAdmin and enable passwordless
    # connect, so an admin opening pgAdmin on the server sees the jotflow DB
    # ready to browse. NOTE: this is an admin convenience only - the browser
    # login flow (user hits the IP) goes through the backend + DB and does NOT
    # use pgAdmin. pgAdmin is installed by the EnterpriseDB PostgreSQL installer
    # by default (we never pass --disable-components), so it is already present.
    param(
        [Parameter(Mandatory)][string]$InstallDir,
        [string]$DbName = 'jotflow',
        [string]$DbUser = 'jotflow',
        [Parameter(Mandatory)][string]$AppDbPassword,
        [int]$Port = 5432
    )
    Write-StepHeader -Number 13 -Total 25 -Title 'Configuring pgAdmin auto-connect'

    # 1. Locate pgAdmin 4 (bundled with the PostgreSQL installer).
    $pgAdminExe = Get-ChildItem 'C:\Program Files\PostgreSQL\*\pgAdmin 4\bin\pgAdmin4.exe' -ErrorAction SilentlyContinue |
                  Select-Object -First 1 -ExpandProperty FullName
    if (-not $pgAdminExe) {
        $pgAdminExe = Get-ChildItem 'C:\Program Files\pgAdmin 4\*\runtime\pgAdmin4.exe' -ErrorAction SilentlyContinue |
                      Select-Object -First 1 -ExpandProperty FullName
    }
    if (-not $pgAdminExe) {
        Write-Log -Level WARN -Message 'pgAdmin 4 not found - skipping auto-connect. (DB and browser login are unaffected.)'
        return
    }
    Write-Log -Level INFO -Message "pgAdmin found: $pgAdminExe"

    # 2. servers.json - an importable connection definition. pgAdmin never
    #    stores the password in servers.json by design; passwordless connect is
    #    handled by pgpass.conf (step 3).
    $pgaDir = Join-Path $InstallDir 'pgadmin'
    if (-not (Test-Path $pgaDir)) { New-Item -ItemType Directory -Force -Path $pgaDir | Out-Null }
    $serversJson = @"
{
  "Servers": {
    "1": {
      "Name": "FlowAccel ($DbName)",
      "Group": "FlowAccel",
      "Host": "127.0.0.1",
      "Port": $Port,
      "MaintenanceDB": "$DbName",
      "Username": "$DbUser",
      "SSLMode": "prefer",
      "Comment": "FlowAccel application database (auto-configured by installer)"
    }
  }
}
"@
    $serversPath = Join-Path $pgaDir 'servers.json'
    [System.IO.File]::WriteAllText($serversPath, $serversJson)
    Write-Log -Level INFO -Message "pgAdmin servers.json written: $serversPath"

    # 3. pgpass.conf - passwordless DB auth for the current user (no prompt on
    #    connect). Format host:port:db:user:password; ':' and '\' are escaped.
    $escPwd = ($AppDbPassword -replace '\\','\\') -replace ':','\:'
    $pgpassDir = Join-Path $env:APPDATA 'postgresql'
    if (-not (Test-Path $pgpassDir)) { New-Item -ItemType Directory -Force -Path $pgpassDir | Out-Null }
    $pgpassPath = Join-Path $pgpassDir 'pgpass.conf'
    Set-Content -Path $pgpassPath -Value "127.0.0.1:${Port}:${DbName}:${DbUser}:${escPwd}" -Encoding ASCII
    Write-Log -Level INFO -Message "pgpass.conf written (passwordless connect): $pgpassPath"

    # 4. Best-effort: pre-load the server into pgAdmin's profile via the bundled
    #    python setup.py. Desktop pgAdmin is per-user and version-specific, so
    #    this is non-fatal; the documented one-click import is the fallback.
    $loaded = $false
    $pgRoot = Split-Path -Parent (Split-Path -Parent $pgAdminExe)
    $py    = Join-Path $pgRoot 'python\python.exe'
    $setup = Join-Path $pgRoot 'web\setup.py'
    if ((Test-Path $py) -and (Test-Path $setup)) {
        # pgAdmin's load-servers CLI changed across versions: some require
        # --user, some auto-target the desktop user, some use a 'load-servers'
        # subcommand. Try the known variants until one succeeds (all non-fatal).
        $variants = @(
            @('--load-servers', $serversPath, '--user', 'pgadmin4@pgadmin.org'),
            @('--load-servers', $serversPath),
            @('load-servers', $serversPath, '--user', 'pgadmin4@pgadmin.org')
        )
        foreach ($v in $variants) {
            if ($loaded) { break }
            try {
                & $py $setup @v 2>&1 | ForEach-Object { Write-Log -Level DEBUG -Message $_ }
                if ($LASTEXITCODE -eq 0) { $loaded = $true }
            } catch { Write-Log -Level DEBUG -Message "pgAdmin load-servers variant failed: $($_.Exception.Message)" }
        }
    }

    # 5. Desktop shortcut to pgAdmin for the operator.
    try {
        $sc = Join-Path ([Environment]::GetFolderPath('CommonDesktopDirectory')) 'FlowAccel Database (pgAdmin).lnk'
        $sh = New-Object -ComObject WScript.Shell
        $lnk = $sh.CreateShortcut($sc)
        $lnk.TargetPath = $pgAdminExe
        $lnk.Save()
    } catch {}

    if ($loaded) {
        Write-Log -Level OK -Message 'pgAdmin auto-connect configured (server pre-loaded + passwordless).'
    } else {
        Write-Log -Level OK -Message "pgAdmin ready (passwordless via pgpass). If the FlowAccel server is not auto-listed, import it once: pgAdmin > Tools > Import/Export Servers > $serversPath"
    }
}

function Grant-AppDbPrivileges {
    # Belt-and-suspenders for the "permission denied for table users" failure.
    # In this architecture migrate.js connects AS the app role (jotflow), so it
    # already owns every table and no grant is strictly needed. But if a schema
    # object ever gets created by the postgres superuser (manual fix, future
    # migration), the app role would lose access. This grant + ALTER DEFAULT
    # PRIVILEGES makes that impossible. Idempotent and safe to re-run.
    param(
        [Parameter(Mandatory)][string]$SuperPassword,
        [string]$DbName = 'jotflow',
        [string]$DbUser = 'jotflow',
        [int]$Port = 5432
    )
    $psql = Get-PsqlPath
    if (-not $psql) { throw 'psql.exe not found; PostgreSQL install incomplete.' }
    $sql = @"
GRANT ALL ON SCHEMA public TO $DbUser;
GRANT ALL ON ALL TABLES IN SCHEMA public TO $DbUser;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO $DbUser;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO $DbUser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $DbUser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $DbUser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO $DbUser;
"@
    $tmp = New-TemporaryFile
    Set-Content -Path $tmp -Value $sql -Encoding ASCII
    $env:PGPASSWORD = $SuperPassword
    try {
        & $psql -h 127.0.0.1 -p $Port -U postgres -d $DbName -f $tmp.FullName 2>&1 |
            ForEach-Object { Write-Log -Level DEBUG -Message $_ }
        Write-Log -Level OK -Message "Privileges granted on '$DbName' to role '$DbUser'."
    } finally {
        Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue
        Remove-Item $tmp -Force -ErrorAction SilentlyContinue
    }
}

function Invoke-DbMigration {
    param(
        [Parameter(Mandatory)][string]$BackendPath
    )
    Write-StepHeader -Number 13 -Total 25 -Title 'Applying database schema'
    $migrate = Join-Path $BackendPath 'db\migrate.js'
    if (-not (Test-Path $migrate)) { throw "migrate.js not found at $migrate" }
    Push-Location $BackendPath
    try {
        & node 'db\migrate.js' 2>&1 | ForEach-Object { Write-Log -Level DEBUG -Message $_ }
        if ($LASTEXITCODE -ne 0) { throw "DB migration failed (exit $LASTEXITCODE)" }
    } finally {
        Pop-Location
    }
    Write-Log -Level OK -Message 'Database schema applied.'
}
