# site.ps1 - Steps 10-11, 14-15: Deploy app files, .env, NTFS perms, IIS site.

function Copy-AppFiles {
    param(
        [Parameter(Mandatory)][string]$PayloadAppDir,
        [Parameter(Mandatory)][string]$InstallDir
    )
    Write-StepHeader -Number 10 -Total 25 -Title 'Deploying application files'
    if (-not (Test-Path $PayloadAppDir)) { throw "Payload app dir not found: $PayloadAppDir" }
    if (-not (Test-Path $InstallDir))   { New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null }

    # Preserve existing .env if any
    $envFile = Join-Path $InstallDir 'backend\.env'
    $backup = $null
    if (Test-Path $envFile) {
        $backup = Join-Path $env:TEMP "flowaccel-env-backup-$([guid]::NewGuid()).env"
        Copy-Item $envFile $backup -Force
        Write-Log -Level INFO -Message "Existing .env backed up to $backup"
    }

    $items = @('dist','backend','server.js')
    foreach ($i in $items) {
        $src = Join-Path $PayloadAppDir $i
        if (-not (Test-Path $src)) {
            Write-Log -Level WARN -Message "Payload item missing: $i"
            continue
        }
        $dst = Join-Path $InstallDir $i
        Write-Log -Level INFO -Message "Copying $i ..."
        if ((Get-Item $src).PSIsContainer) {
            robocopy $src $dst /MIR /NFL /NDL /NJH /NJS /NP /XD node_modules logs uploads | Out-Null
        } else {
            Copy-Item $src $dst -Force
        }
    }

    # web.config must sit INSIDE the IIS site root, which is the dist\ folder
    # (New-FlowAccelSite is called with -PhysicalPath ...\dist). IIS only reads
    # web.config from a site's physical path, so a copy at the install root is
    # never loaded — SPA routing and the /api proxy would silently break, and a
    # bare site root with no index.html returns HTTP 403.14.
    $webCfgSrc = Join-Path $PayloadAppDir 'web.config'
    if (Test-Path $webCfgSrc) {
        Copy-Item $webCfgSrc (Join-Path $InstallDir 'dist\web.config') -Force
        Write-Log -Level INFO -Message 'Deployed web.config into dist\ (IIS site root).'
    } else {
        Write-Log -Level WARN -Message 'Payload item missing: web.config'
    }

    # Recreate runtime dirs
    foreach ($d in @('uploads\avatars','uploads\signatures','logs')) {
        $p = Join-Path $InstallDir $d
        if (-not (Test-Path $p)) { New-Item -ItemType Directory -Force -Path $p | Out-Null }
    }
    Write-Log -Level OK -Message 'App files deployed.'
    return $backup
}

function Write-DotEnv {
    param(
        [Parameter(Mandatory)][string]$InstallDir,
        [Parameter(Mandatory)][hashtable]$Config
    )
    Write-StepHeader -Number 11 -Total 25 -Title 'Generating backend .env'
    $envPath = Join-Path $InstallDir 'backend\.env'

    $sessionSecret = $Config.SessionSecret
    if (-not $sessionSecret) {
        Add-Type -AssemblyName System.Web
        $sessionSecret = [System.Web.Security.Membership]::GeneratePassword(64,16)
    }

    $dbPwEsc = $Config.AppDbPassword -replace '@','%40' -replace '#','%23'
    $databaseUrl = "postgres://$($Config.DbUser):$dbPwEsc@127.0.0.1:$($Config.PgPort)/$($Config.DbName)"
    $allowedOrigin = "https://$($Config.ServerIP)"

    $lines = @(
        "# Auto-generated by FlowAccel installer $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
        "DATABASE_URL=$databaseUrl",
        "SESSION_SECRET=$sessionSecret",
        "PORT=$($Config.BackendPort)",
        "NODE_ENV=production",
        "ALLOWED_ORIGIN=$allowedOrigin",
        "JOTFORM_API_KEY=$($Config.JotformApiKey)",
        "JOTFORM_TEAM_ID=$($Config.JotformTeamId)",
        "JOTFORM_BASE=$($Config.JotformBase)",
        "JOTFORM_HOST=$($Config.JotformHost)",
        "JOTFORM_WEBHOOK_SECRET=$($Config.JotformWebhookSecret)",
        "MICROSOFT_CLIENT_ID=$($Config.MicrosoftClientId)",
        "MICROSOFT_TENANT_ID=$($Config.MicrosoftTenantId)",
        "MICROSOFT_CLIENT_SECRET=$($Config.MicrosoftClientSecret)",
        "MICROSOFT_REDIRECT_URI=$($Config.MicrosoftRedirectUri)"
    )
    $lines -join "`r`n" | Set-Content -Path $envPath -Encoding ASCII

    # Lock down ACL: SYSTEM, Administrators, the service account, read.
    try {
        icacls $envPath /inheritance:r | Out-Null
        icacls $envPath /grant 'SYSTEM:(R)' 'Administrators:(R)' 'IIS_IUSRS:(R)' | Out-Null
    } catch {
        Write-Log -Level WARN -Message ".env ACL hardening failed: $($_.Exception.Message)"
    }
    Write-Log -Level OK -Message ".env written at $envPath (ACL locked to SYSTEM/Administrators/IIS_IUSRS)."
}

function Set-NTFSPermissions {
    param([Parameter(Mandatory)][string]$InstallDir)
    Write-StepHeader -Number 14 -Total 25 -Title 'Setting NTFS permissions'
    # Modify on install root (recursive)
    icacls $InstallDir /grant 'IIS_IUSRS:(OI)(CI)M' 'IUSR:(OI)(CI)M' /T /C | Out-Null
    foreach ($d in @('uploads','logs')) {
        $p = Join-Path $InstallDir $d
        if (Test-Path $p) {
            icacls $p /grant 'IIS_IUSRS:(OI)(CI)F' 'IUSR:(OI)(CI)F' /T /C | Out-Null
        }
    }
    Write-Log -Level OK -Message 'NTFS permissions applied.'
}

function New-FlowAccelSite {
    param(
        [Parameter(Mandatory)][string]$SiteName,
        [Parameter(Mandatory)][string]$AppPoolName,
        [Parameter(Mandatory)][string]$PhysicalPath,
        [int]$HttpPort = 80
    )
    Write-StepHeader -Number 15 -Total 25 -Title "Creating IIS site '$SiteName'"
    Import-Module WebAdministration -ErrorAction Stop

    # Always retire 'Default Web Site' so the bare-IP URL can never land on the IIS welcome page.
    $dws = Get-Website -Name 'Default Web Site' -ErrorAction SilentlyContinue
    if ($dws) {
        Stop-Website -Name 'Default Web Site' -ErrorAction SilentlyContinue
        Set-ItemProperty 'IIS:\Sites\Default Web Site' -Name serverAutoStart -Value $false -ErrorAction SilentlyContinue
        Write-Log -Level INFO -Message "Default Web Site stopped and disabled (was: $($dws.State))."
    }

    # Drop existing site/pool to converge on clean state
    if (Get-Website -Name $SiteName -ErrorAction SilentlyContinue) {
        Stop-Website -Name $SiteName -ErrorAction SilentlyContinue
        Remove-Website -Name $SiteName
    }
    if (Test-Path "IIS:\AppPools\$AppPoolName") {
        Remove-WebAppPool -Name $AppPoolName
    }

    New-WebAppPool -Name $AppPoolName | Out-Null
    Set-ItemProperty "IIS:\AppPools\$AppPoolName" -Name managedRuntimeVersion -Value ''
    Set-ItemProperty "IIS:\AppPools\$AppPoolName" -Name startMode -Value 'AlwaysRunning'

    New-Website -Name $SiteName -PhysicalPath $PhysicalPath `
        -ApplicationPool $AppPoolName -Port $HttpPort -Force | Out-Null

    Write-Log -Level OK -Message "Site '$SiteName' created on port $HttpPort (pool '$AppPoolName')."
}

function Start-FlowAccelSite {
    param([Parameter(Mandatory)][string]$SiteName)
    Write-StepHeader -Number 23 -Total 25 -Title "Starting IIS site '$SiteName'"
    Import-Module WebAdministration -ErrorAction Stop
    Start-Website -Name $SiteName -ErrorAction Stop
    Write-Log -Level OK -Message "Site '$SiteName' started."
}
